### ISSUE TITLE
Fonts is to small on hires screen

### ISSUE THREAD

**Issue by hooddy** [basharast/DuckStation-UWP-ARM#1]
Please fix font issue
![wp_ss_20230903_0001](https://github.com/basharast/DuckStation-UWP-ARM/assets/6899176/9b3f1005-bb5d-4c12-9003-f63d355618d3)
![wp_ss_20230903_0002](https://github.com/basharast/DuckStation-UWP-ARM/assets/6899176/894a0c22-8b08-4e29-9ee2-f856bdd24c87)
And my GPU) (it is Xiaomi Mi4 LTE phone)

**Comment by basharast** [comment]
Hi, those phones are not supported yet, I will add this in the next update
as for font, size it's better to use this in Landscape mode.

**Comment by basharast** [comment]
Whenever you have time, can you please install this app
https://www.microsoft.com/store/productId/9WZDNCRFK07L

and let me know what it will show about your GPU details (few screenshots will be good)
many thanks.

**Comment by hooddy** [comment]
> Hi, those phones are not supported yet, I will add this in the next update as for font, size it's better to use this in Landscape mode.

Landscape mode isn't help much. Fonts is very small to view. And app crush right after run in landscape.

**Comment by hooddy** [comment]
> Whenever you have time, can you please install this app https://www.microsoft.com/store/productId/9WZDNCRFK07L
> 
> and let me know what it will show about your GPU details (few screenshots will be good) many thanks.

![wp_ss_20230904_0001](https://github.com/basharast/DuckStation-UWP-ARM/assets/6899176/51876d07-beba-4a8c-a41f-187d229a257f)
![wp_ss_20230904_0002](https://github.com/basharast/DuckStation-UWP-ARM/assets/6899176/1ff690f3-cb00-4050-a5f8-1926ecc88f10)
![wp_ss_20230904_0003](https://github.com/basharast/DuckStation-UWP-ARM/assets/6899176/e1d29e9b-c3f7-440c-a51e-d809a6c4e1d2)

**Comment by basharast** [comment]
Many thanks, I will try to solve this in the next update.

**Comment by basharast** [comment]
Font size on vertical mode has been fixed in 1.0.3

<img src="https://github.com/basharast/DuckStation-UWP-ARM/assets/3244951/24d96882-01f1-448d-a7cb-ac2f24310447" width="600">
