### ISSUE TITLE
Autorotate crush

### ISSUE THREAD

**Issue by hooddy** [basharast/DuckStation-UWP-ARM#2]
DS is crash after autorotate.

**Comment by basharast** [comment]
Based on this issue: #1, your phone's GPU is not supported yet
I think it will be solved once the support added.

**Comment by basharast** [comment]
I published [new update](https://github.com/basharast/DuckStation-UWP-ARM/releases/tag/1.0.2),

## Rotate crash
This happens on builds 15035 with feature level 9.3
so get the `LandScape` version instead

**Comment by basharast** [comment]
Thanks for reporting this issue it was important
now fixed in 1.0.3
