### ISSUE TITLE
Can not change BIOS directory

### ISSUE THREAD

**Issue by hooddy** [basharast/DuckStation-UWP-ARM#3]
There is no button to select BIOS directory but to look for it.
![wp_ss_20230903_0003](https://github.com/basharast/DuckStation-UWP-ARM/assets/6899176/0352ffe8-0171-4f45-83f0-847b439ce40b)

**Comment by basharast** [comment]
if you want to select the current folder you need to choose `<Use this Directory>`
but it's better to re-locate the whole storage from Main Menu:
- at the end `Storage`
- Choose new folder

now in the new folder you will find many folders related to duckstation one of them is `bios`
put the files inside it
